import React, { useContext, useMemo, useState, useEffect } from 'react'
import { AuthContext } from '../context/AuthContext'
import useApi from '../hooks/useApi'
import categories from '../utils/categories'
import { formatCurrency } from '../utils/format'
import AddModal from '../components/AddTransactionModal'
import TransactionTable from '../components/TransactionTable'
import PieChartComponent from '../charts/PieChartComponent'
import BarChartComponent from '../charts/BarChartComponent'
export default function Dashboard(){ const { user, signOut } = useContext(AuthContext); const api = useApi(); const [transactions, setTransactions] = useState([]); const [showAdd,setShowAdd]=useState(false); const [categoryFilter,setCategoryFilter]=useState('All'); const [rangeFilter,setRangeFilter]=useState('This Month')
  useEffect(()=>{ fetchList() },[])
  async function fetchList(){ try{ const res = await api.get('/expenses'); setTransactions(res.data) }catch(e){ console.error(e) } }
  async function add(tx){ try{ await api.post('/expenses', tx); fetchList() }catch(e){ console.error(e) } }
  async function remove(i){ try{ const id = transactions[i]._id; await api.delete(`/expenses/${id}`); fetchList() }catch(e){ console.error(e) } }
  const filtered = useMemo(()=>{ let list = transactions||[]; if(categoryFilter && categoryFilter!=='All') list=list.filter(t=>t.category===categoryFilter); const now=new Date(); if(rangeFilter==='Today'){ const s=new Date(now.getFullYear(),now.getMonth(),now.getDate()).toISOString().slice(0,10); list=list.filter(t=>t.date && t.date.slice(0,10)===s) } else if(rangeFilter==='This Week'){ const start=new Date(now); start.setDate(now.getDate()-7); list=list.filter(t=> new Date(t.date) >= start ) } else if(rangeFilter==='This Month'){ const m=now.toISOString().slice(0,7); list=list.filter(t=> t.date && t.date.slice(0,7)===m ) } return list },[transactions,categoryFilter,rangeFilter])
  const totals = useMemo(()=>{ const income=(filtered||[]).filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount||0),0); const expense=(filtered||[]).filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount||0),0); const remaining=income-expense; return {income,expense,remaining} },[filtered])
  return (<div className='app'><header className='topbar'><h1>Expense Tracker - {user.name}</h1><div style={{display:'flex',gap:8,alignItems:'center'}}><div className='summary-card'>Remaining: <strong>{formatCurrency(totals.remaining)}</strong></div><button className='btn' onClick={()=>setShowAdd(true)}>Add</button><button className='btn ghost' onClick={signOut}>Sign out</button></div></header><div className='container'><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'center'}}><label>Category: <select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)} className='input'><option>All</option>{categories.map(c=> <option key={c} value={c}>{c}</option>)}</select></label><label>Range: <select value={rangeFilter} onChange={e=>setRangeFilter(e.target.value)} className='input'><option>This Month</option><option>This Week</option><option>Today</option><option>All Time</option></select></label></div><section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:12}}><div className='panel'><h3>Expense Split</h3><PieChartComponent data={filtered} /></div><div className='panel'><h3>Monthly / Range Summary</h3><BarChartComponent data={filtered} /></div></section><section className='panel' style={{marginTop:12}}><h3>Recent Transactions</h3><TransactionTable list={filtered} onDelete={(i)=>remove(i)} /></section></div><AddModal open={showAdd} onClose={()=>setShowAdd(false)} onSave={(tx)=>{ add(tx); setShowAdd(false) }} /></div>)}
